<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Azure -->
    <PackageVersion Include="Microsoft.ApplicationInsights" Version="2.23.0" />
    <PackageVersion Include="Microsoft.Azure.Cosmos" Version="3.35.4" />
    <!-- JSON Serialization -->
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="NodaTime.Serialization.JsonNet" Version="3.3.0" />
    <PackageVersion Include="NodaTime.Serialization.SystemTextJson" Version="1.4.0" />
    <PackageVersion Include="System.Text.Json" Version="8.0.6" />
    <!-- Testing -->
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="NUnit" Version="4.6.1" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.14.0" />
    <PackageVersion Include="RandomGen" Version="1.1.6" />
    <PackageVersion Include="SpecFlow" Version="3.9.74" />
    <PackageVersion Include="SpecFlow.NUnit.Runners" Version="3.9.74" />
    <PackageVersion Include="SpecFlow.Tools.MsBuild.Generation" Version="3.9.74" />
  </ItemGroup>
</Project>