<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="StoredProcedures\BulkDelete.js" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="StoredProcedures\BulkDelete.js" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
</Project>